"""Export a :class:`QuantModel` to a self-contained C header (``model_data.h``).

The generated header defines all INT8 weights, Q.F biases, requant multipliers,
the embedding table and the gated-activation LUTs, wired into a ``QModel`` struct
the hand-written C runtime consumes. Keeping the LUTs in the same generated file
guarantees the C runtime uses byte-identical tables to the Python reference.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from .fixedpoint import FRAC_BITS, LUT_RANGE, LUT_SIZE, make_sigmoid_lut, make_tanh_lut
from .int_infer import IntegerRuntime  # noqa: F401  (re-exported convenience)
from .quantizer import QuantConv, QuantModel

__all__ = ["export_c_header"]


def _c_array(name: str, values: np.ndarray, ctype: str) -> str:
    flat = np.asarray(values).reshape(-1)
    body = ", ".join(str(int(v)) for v in flat)
    return f"static const {ctype} {name}[{flat.size}] = {{ {body} }};\n"


def _emit_conv(prefix: str, conv: QuantConv) -> tuple[str, str]:
    """Return (array-definitions, QConv-initializer) for one conv."""
    out_ch, in_ch, kernel = conv.weight.shape
    defs = _c_array(f"{prefix}_w", conv.weight, "int8_t")
    defs += _c_array(f"{prefix}_b", conv.bias_qf, "int32_t")
    init = (
        f"{{ {prefix}_w, {prefix}_b, {out_ch}, {in_ch}, {kernel}, "
        f"{conv.dilation}, {conv.multiplier}, {conv.shift} }}"
    )
    return defs, init


def export_c_header(qm: QuantModel, path: str | Path) -> Path:
    """Write ``model_data.h`` for the C runtime and return the path."""
    lines: list[str] = []
    lines.append("/* Auto-generated by signalmint.quantize.export -- do not edit. */\n")
    lines.append("#ifndef SIGNALMINT_MODEL_DATA_H\n#define SIGNALMINT_MODEL_DATA_H\n")
    lines.append('#include "signalmint_rt.h"\n\n')

    lines.append(f"#define SM_NUM_BINS {qm.num_bins}\n")
    lines.append(f"#define SM_RES_CH {qm.residual_channels}\n")
    lines.append(f"#define SM_SKIP_CH {qm.skip_channels}\n")
    lines.append(f"#define SM_KERNEL {qm.kernel_size}\n")
    lines.append(f"#define SM_NUM_LAYERS {len(qm.blocks)}\n")
    lines.append(f"#define SM_DIL_CYCLE {qm.dilation_cycle}\n")
    lines.append(f"#define SM_FRAC_BITS {FRAC_BITS}\n")
    lines.append(f"#define SM_LUT_SIZE {LUT_SIZE}\n")
    lines.append(f"#define SM_LUT_RANGE {LUT_RANGE}\n\n")

    # Embedding table (num_bins x res_ch), row-major.
    lines.append(_c_array("sm_embed", qm.embed_qf, "int32_t"))

    # LUTs.
    lines.append(_c_array("sm_tanh_lut", make_tanh_lut(), "int32_t"))
    lines.append(_c_array("sm_sigmoid_lut", make_sigmoid_lut(), "int32_t"))
    lines.append("\n")

    conv_inits: list[str] = []
    res_inits: list[str] = []
    skip_inits: list[str] = []
    for i, blk in enumerate(qm.blocks):
        d, init = _emit_conv(f"sm_l{i}_conv", blk.conv)
        lines.append(d)
        conv_inits.append(init)
        d, init = _emit_conv(f"sm_l{i}_res", blk.residual)
        lines.append(d)
        res_inits.append(init)
        d, init = _emit_conv(f"sm_l{i}_skip", blk.skip)
        lines.append(d)
        skip_inits.append(init)

    d, head1_init = _emit_conv("sm_head1", qm.head1)
    lines.append(d)
    d, head2_init = _emit_conv("sm_head2", qm.head2)
    lines.append(d)
    lines.append("\n")

    lines.append("static const QConv sm_conv_layers[SM_NUM_LAYERS] = {\n  "
                 + ",\n  ".join(conv_inits) + "\n};\n")
    lines.append("static const QConv sm_res_layers[SM_NUM_LAYERS] = {\n  "
                 + ",\n  ".join(res_inits) + "\n};\n")
    lines.append("static const QConv sm_skip_layers[SM_NUM_LAYERS] = {\n  "
                 + ",\n  ".join(skip_inits) + "\n};\n\n")

    lines.append(
        "static const QModel signalmint_model = {\n"
        f"  SM_NUM_BINS, SM_RES_CH, SM_SKIP_CH, SM_KERNEL, SM_NUM_LAYERS, SM_DIL_CYCLE,\n"
        f"  sm_embed, sm_conv_layers, sm_res_layers, sm_skip_layers,\n"
        f"  {head1_init}, {head2_init},\n"
        f"  sm_tanh_lut, sm_sigmoid_lut\n"
        "};\n\n"
    )

    lines.append("#endif /* SIGNALMINT_MODEL_DATA_H */\n")

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("".join(lines), encoding="utf-8")
    return p
